display_name: FlClash

icon: ./assets/images/icon.png

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true
startup_wm_class: com.follow.clash

include: []